<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Estimation | Data Analytics with R</title>
  <meta name="description" content="Chapter 4 Estimation | Data Analytics with R" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Estimation | Data Analytics with R" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Estimation | Data Analytics with R" />
  
  
  

<meta name="author" content="Adam Smith (main text), UCL School of Management" />
<meta name="author" content="Rafael Greminger (2022 updates), UCL School of Management" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="sampling-distributions-and-the-clt.html"/>
<link rel="next" href="hypothesis-tests.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html"><i class="fa fa-check"></i>Getting Started with R</a>
<ul>
<li class="chapter" data-level="" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#why-use-r"><i class="fa fa-check"></i>Why use R?</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#what-does-r-do"><i class="fa fa-check"></i>What does R do?</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#downloading-r-and-rstudio"><i class="fa fa-check"></i>Downloading R and RStudio</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#installing-and-loading-packages"><i class="fa fa-check"></i>Installing and Loading Packages</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-data-analytics.html"><a href="introduction-to-data-analytics.html"><i class="fa fa-check"></i><b>1</b> Introduction to Data Analytics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-data-analytics.html"><a href="introduction-to-data-analytics.html#loading-and-inspecting-data-sets"><i class="fa fa-check"></i><b>1.1</b> Loading and Inspecting Data Sets</a></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-data-analytics.html"><a href="introduction-to-data-analytics.html#statistical-summaries"><i class="fa fa-check"></i><b>1.2</b> Statistical Summaries</a></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-data-analytics.html"><a href="introduction-to-data-analytics.html#graphical-summaries"><i class="fa fa-check"></i><b>1.3</b> Graphical Summaries</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="computing-probabilities.html"><a href="computing-probabilities.html"><i class="fa fa-check"></i><b>2</b> Computing Probabilities</a>
<ul>
<li class="chapter" data-level="2.1" data-path="computing-probabilities.html"><a href="computing-probabilities.html#normal-distribution"><i class="fa fa-check"></i><b>2.1</b> Normal Distribution</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="computing-probabilities.html"><a href="computing-probabilities.html#probability-density-function-dnorm"><i class="fa fa-check"></i><b>2.1.1</b> Probability Density Function (<code>dnorm</code>)</a></li>
<li class="chapter" data-level="2.1.2" data-path="computing-probabilities.html"><a href="computing-probabilities.html#cumulative-distribution-function-pnorm"><i class="fa fa-check"></i><b>2.1.2</b> Cumulative Distribution Function (<code>pnorm</code>)</a></li>
<li class="chapter" data-level="2.1.3" data-path="computing-probabilities.html"><a href="computing-probabilities.html#quantile-function-qnorm"><i class="fa fa-check"></i><b>2.1.3</b> Quantile Function (<code>qnorm</code>)</a></li>
<li class="chapter" data-level="2.1.4" data-path="computing-probabilities.html"><a href="computing-probabilities.html#random-number-generator-rnorm"><i class="fa fa-check"></i><b>2.1.4</b> Random Number Generator (<code>rnorm</code>)</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="computing-probabilities.html"><a href="computing-probabilities.html#bernoulli-and-binomial-distributions"><i class="fa fa-check"></i><b>2.2</b> Bernoulli and Binomial Distributions</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="computing-probabilities.html"><a href="computing-probabilities.html#probability-mass-function-dbinom"><i class="fa fa-check"></i><b>2.2.1</b> Probability Mass Function (<code>dbinom</code>)</a></li>
<li class="chapter" data-level="2.2.2" data-path="computing-probabilities.html"><a href="computing-probabilities.html#cumulative-distribution-function-pbinom"><i class="fa fa-check"></i><b>2.2.2</b> Cumulative Distribution Function (<code>pbinom</code>)</a></li>
<li class="chapter" data-level="2.2.3" data-path="computing-probabilities.html"><a href="computing-probabilities.html#quantile-function-qbinom"><i class="fa fa-check"></i><b>2.2.3</b> Quantile Function (<code>qbinom</code>)</a></li>
<li class="chapter" data-level="2.2.4" data-path="computing-probabilities.html"><a href="computing-probabilities.html#random-number-generator-rbinom"><i class="fa fa-check"></i><b>2.2.4</b> Random Number Generator (<code>rbinom</code>)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="sampling-distributions-and-the-clt.html"><a href="sampling-distributions-and-the-clt.html"><i class="fa fa-check"></i><b>3</b> Sampling Distributions and the CLT</a></li>
<li class="chapter" data-level="4" data-path="estimation.html"><a href="estimation.html"><i class="fa fa-check"></i><b>4</b> Estimation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="estimation.html"><a href="estimation.html#point-estimation"><i class="fa fa-check"></i><b>4.1</b> Point Estimation</a></li>
<li class="chapter" data-level="4.2" data-path="estimation.html"><a href="estimation.html#confidence-intervals"><i class="fa fa-check"></i><b>4.2</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="estimation.html"><a href="estimation.html#types-of-confidence-intervals"><i class="fa fa-check"></i><b>4.2.1</b> Types of Confidence Intervals</a></li>
<li class="chapter" data-level="4.2.2" data-path="estimation.html"><a href="estimation.html#interpreting-confidence-intervals"><i class="fa fa-check"></i><b>4.2.2</b> Interpreting confidence intervals</a></li>
<li class="chapter" data-level="4.2.3" data-path="estimation.html"><a href="estimation.html#examples"><i class="fa fa-check"></i><b>4.2.3</b> Examples</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html"><i class="fa fa-check"></i><b>5</b> Hypothesis Tests</a>
<ul>
<li class="chapter" data-level="5.1" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html#steps-of-hypothesis-testing"><i class="fa fa-check"></i><b>5.1</b> Steps of Hypothesis Testing</a></li>
<li class="chapter" data-level="5.2" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html#connection-to-confidence-intervals"><i class="fa fa-check"></i><b>5.2</b> Connection to Confidence Intervals</a></li>
<li class="chapter" data-level="5.3" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html#hypothesis-testing-in-r"><i class="fa fa-check"></i><b>5.3</b> Hypothesis Testing in R</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>6</b> Regression</a>
<ul>
<li class="chapter" data-level="6.1" data-path="regression.html"><a href="regression.html#linear-regression"><i class="fa fa-check"></i><b>6.1</b> Linear Regression</a></li>
<li class="chapter" data-level="6.2" data-path="regression.html"><a href="regression.html#regression-trees"><i class="fa fa-check"></i><b>6.2</b> Regression Trees</a></li>
<li class="chapter" data-level="6.3" data-path="regression.html"><a href="regression.html#model-selection"><i class="fa fa-check"></i><b>6.3</b> Model Selection</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>7</b> Classification</a>
<ul>
<li class="chapter" data-level="7.1" data-path="classification.html"><a href="classification.html#k-nearest-neighbors"><i class="fa fa-check"></i><b>7.1</b> <span class="math inline">\(k\)</span>-Nearest Neighbors</a></li>
<li class="chapter" data-level="7.2" data-path="classification.html"><a href="classification.html#logistic-regression"><i class="fa fa-check"></i><b>7.2</b> Logistic Regression</a></li>
<li class="chapter" data-level="7.3" data-path="classification.html"><a href="classification.html#classification-trees"><i class="fa fa-check"></i><b>7.3</b> Classification Trees</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i><b>8</b> Clustering</a>
<ul>
<li class="chapter" data-level="8.1" data-path="clustering.html"><a href="clustering.html#k-means"><i class="fa fa-check"></i><b>8.1</b> <span class="math inline">\(k\)</span>-Means</a></li>
<li class="chapter" data-level="8.2" data-path="clustering.html"><a href="clustering.html#hierarchical-clustering"><i class="fa fa-check"></i><b>8.2</b> Hierarchical Clustering</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Analytics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estimation" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Estimation<a href="estimation.html#estimation" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="point-estimation" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Point Estimation<a href="estimation.html#point-estimation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<hr>
<p>Point estimation is all about using one single number (statistic) to estimate a population parameter of interest. Generally, we need to differentiate three different terms:</p>
<ol style="list-style-type: decimal">
<li><em>Parameter</em>: <span class="math inline">\(\theta\)</span></li>
<li><em>Estimator</em>: <span class="math inline">\(\hat{\theta}(X) = g(X_1,\dots,X_n)\)</span></li>
<li><em>Estimate</em>: <span class="math inline">\(\hat{\theta}(x) = g(x_1,\dots,x_n)\)</span></li>
</ol>
<p><span class="math inline">\(\theta\)</span> is the population parameter we want to know. <span class="math inline">\(\hat{\theta}(X)\)</span> is our estimator, which is a function of our random sample. It is itself a random variable because another random sample will lead to a different number. The estimate <span class="math inline">\(\hat{\theta}(x)\)</span> then is our statistic that we compute for given sample; given realizations <span class="math inline">\((x_1,\dots,x_n)\)</span>, this number is not random. Note that we apply the same function <span class="math inline">\(g()\)</span> in the estimator and estimate, but in the estimator the <span class="math inline">\(X_i\)</span> are random variables whereas in the estimate the <span class="math inline">\(x_i\)</span> are realizations.</p>
<p>To highlight the difference between estimate and estimator consider the following example: the population is 1,000,000 consumers and we want to know how many of them purchased our product. Hence, the population parameter we want to know is <span class="math display">\[\theta = \frac{\text{no. purchases in population}}{1,000,000}\]</span></p>
<p>In principle, we could just call all 1,000,000 consumers and ask, but that would cost way too much time (and time is money)! Instead, we are going to take a <em>random</em> sample with <span class="math inline">\(n\)</span> consumers from the population. In this case, our estimator for the mean is
<span class="math display">\[\hat{\theta}(X) = g(X_1,\dots,X_n) = \frac{\text{no. purchases in sample}}{n} \]</span></p>
<p>This is what we now do in R.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="estimation.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate population and calculate population parameter</span></span>
<span id="cb1-2"><a href="estimation.html#cb1-2" aria-hidden="true" tabindex="-1"></a>pop <span class="ot">=</span> <span class="fu">rbinom</span>(<span class="dv">1000000</span>,<span class="dv">1</span>,<span class="fl">0.2</span>) <span class="co"># generates 1,000,000 consumers that bought (=1) or not(=0)</span></span>
<span id="cb1-3"><a href="estimation.html#cb1-3" aria-hidden="true" tabindex="-1"></a>pop_par <span class="ot">=</span> <span class="fu">mean</span>(pop)  </span>
<span id="cb1-4"><a href="estimation.html#cb1-4" aria-hidden="true" tabindex="-1"></a>pop_par </span></code></pre></div>
<pre><code>## [1] 0.200342</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="estimation.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Take random sample and calculate estimate on that sample</span></span>
<span id="cb3-2"><a href="estimation.html#cb3-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">sample</span>(pop,<span class="dv">100</span>,<span class="at">replace=</span><span class="cn">TRUE</span>)    <span class="co"># randomly takes 100 consumers out of pop </span></span>
<span id="cb3-3"><a href="estimation.html#cb3-3" aria-hidden="true" tabindex="-1"></a>estimate <span class="ot">=</span> <span class="fu">mean</span>(x)</span>
<span id="cb3-4"><a href="estimation.html#cb3-4" aria-hidden="true" tabindex="-1"></a>estimate </span></code></pre></div>
<pre><code>## [1] 0.17</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="estimation.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate sampling error </span></span>
<span id="cb5-2"><a href="estimation.html#cb5-2" aria-hidden="true" tabindex="-1"></a>sampling_error <span class="ot">=</span> <span class="fu">abs</span>(estimate<span class="sc">-</span>pop_par) </span>
<span id="cb5-3"><a href="estimation.html#cb5-3" aria-hidden="true" tabindex="-1"></a>sampling_error</span></code></pre></div>
<pre><code>## [1] 0.030342</code></pre>
<p>Both the estimate and sampling error will be different if we take another random sample.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="estimation.html#cb7-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">sample</span>(pop,<span class="dv">100</span>,<span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb7-2"><a href="estimation.html#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)</span></code></pre></div>
<pre><code>## [1] 0.28</code></pre>
</div>
<div id="confidence-intervals" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Confidence Intervals<a href="estimation.html#confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<hr>
<p>As we just saw, estimators themselves are random variables and subject to variation across different samples. Hence, point estimates are <em>not enough</em> to learn about the population parameter we are interested in. Rather than provide a single point estimate, it will be better to provide a <em>range of plausible values</em> for the parameter of interest. This is the idea of <strong>confidence intervals</strong>.</p>
<p>A confidence interval for any parameter <span class="math inline">\(\theta\)</span> will always take the form:
<span class="math display">\[\hat{\theta}\pm \text{(critical value)}\times \text{SD}(\hat{\theta})\]</span>
where <span class="math inline">\(\hat{\theta}\)</span> is an estimator of <span class="math inline">\(\theta\)</span>, the critical value is a quantile of a normal or t distribution, and <span class="math inline">\(\text{SD}(\hat{\theta})\)</span> is the standard deviation of the estimator.</p>
<div id="types-of-confidence-intervals" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Types of Confidence Intervals<a href="estimation.html#types-of-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will consider four types of <span class="math inline">\((1-\alpha)100\%\)</span> confidence intervals.</p>
<ol style="list-style-type: decimal">
<li><p>Confidence interval for mean <span class="math inline">\(\mu\)</span>, data are normally distributed, variance <span class="math inline">\(\sigma^2\)</span> is known
<span class="math display">\[\bar{x}\pm z_{\alpha/2}{\sigma\over\sqrt{n}}\]</span></p></li>
<li><p>Confidence interval for mean <span class="math inline">\(\mu\)</span>, data are normally distributed, variance <span class="math inline">\(\sigma^2\)</span> is unknown
<span class="math display">\[\bar{x}\pm t_{n-1,\alpha/2}{s\over\sqrt{n}}\]</span></p></li>
<li><p>Confidence interval for mean <span class="math inline">\(\mu\)</span>, data are not normally distributed
<span class="math display">\[\bar{x}\pm t_{n-1,\alpha/2}{s\over\sqrt{n}}\]</span></p></li>
<li><p>Confidence interval for proportion <span class="math inline">\(p\)</span>, data are binary (0s and 1s)
<span class="math display">\[\hat{p}\pm z_{\alpha/2}\sqrt{\hat{p}(1-\hat{p})\over n}\]</span></p></li>
</ol>
<p>Notice that we can compute the critical values in R. If we need <span class="math inline">\(z_{\alpha/2}\)</span>, then we must find the value of a standard normal random variable such that <span class="math inline">\(\alpha/2\)</span> percent of the area is to its right. This is can be found using the normal quantile function <code>qnorm( )</code>!</p>
<p>For example, if <span class="math inline">\(\alpha=0.05\)</span> let’s use <code>qnorm( )</code> to find <span class="math inline">\(z_{0.025}\)</span>.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="estimation.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.025</span>, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">1</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 1.959964</code></pre>
<p>A summary of the most commonly used normal critical values are provided below.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Confidence Level <span class="math inline">\((1-\alpha)\)</span>
</th>
<th style="text-align:center;">
Critical Value <span class="math inline">\(z_{\alpha/2}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
99%
</td>
<td style="text-align:center;">
2.576
</td>
</tr>
<tr>
<td style="text-align:center;">
95%
</td>
<td style="text-align:center;">
1.96
</td>
</tr>
<tr>
<td style="text-align:center;">
90%
</td>
<td style="text-align:center;">
1.645
</td>
</tr>
</tbody>
</table>
<p>Similarly, if we need to compute <span class="math inline">\(t_{n-1,\alpha/2}\)</span> with <span class="math inline">\(\alpha=0.05\)</span> and our data have <span class="math inline">\(n=50\)</span> observations, we can use the <code>qt( )</code> function.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="estimation.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.025</span>, <span class="at">df=</span><span class="dv">50-1</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 2.009575</code></pre>
<p>Notice this critical value is larger than <span class="math inline">\(z_{0.025}\)</span> – this comes from the fact that the t-distribution has fatter tails than the normal distribution. But, it also turns out that a t distribution (which only has one parameter <span class="math inline">\(\nu\)</span> called the “degrees of freedom”) converges to a normal distribution as <span class="math inline">\(\nu\to\infty\)</span>. We can formally check this using <code>qt( )</code>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="estimation.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.025</span>, <span class="at">df=</span><span class="dv">50</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 2.008559</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="estimation.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.025</span>, <span class="at">df=</span><span class="dv">100</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 1.983972</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="estimation.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.025</span>, <span class="at">df=</span><span class="dv">1000</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 1.962339</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="estimation.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.025</span>, <span class="at">df=</span><span class="dv">10000</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 1.960201</code></pre>
<p>Notice how these values approach <span class="math inline">\(z_{0.025}\approx1.96\)</span> as the degrees of freedom parameter gets large.</p>
</div>
<div id="interpreting-confidence-intervals" class="section level3 hasAnchor" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Interpreting confidence intervals<a href="estimation.html#interpreting-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose an analyst tells you that the 95% confidence interval for the population parameter <span class="math inline">\(\theta\)</span> is <span class="math inline">\((0.5,1.5)\)</span>. What can you conclude from this, i.e., what does it mean that we are 95% confident that <span class="math inline">\(\theta\)</span> is in this interval?</p>
<p>What the confidence interval tells us is that if we take many samples from the population and construct the confidence interval for each sample, then in approximately 95% of the samples the constructed confidence interval will include the true population parameter. Note that, same as the estimator, the confidence interval depends on the sample and hence is random.</p>
<p>We can check in R whether this holds using the same population we generated earlier. For this, we are now going to construct a for loop that does the following: (1) take a random sample of size <span class="math inline">\(n=100\)</span> from the population, (2) compute the 95% confidence interval (type 4 above) for the sample, check whether the population parameter lies within the computed confidence interval and store the result in a vector called poppar_in_ci.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="estimation.html#cb21-1" aria-hidden="true" tabindex="-1"></a>R <span class="ot">=</span> <span class="dv">1000</span>                                <span class="co"># how many samples to take </span></span>
<span id="cb21-2"><a href="estimation.html#cb21-2" aria-hidden="true" tabindex="-1"></a>poppar_in_ci <span class="ot">=</span> <span class="fu">double</span>(R)</span>
<span id="cb21-3"><a href="estimation.html#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(r <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>R){</span>
<span id="cb21-4"><a href="estimation.html#cb21-4" aria-hidden="true" tabindex="-1"></a>    x <span class="ot">=</span> <span class="fu">sample</span>(pop,<span class="dv">100</span>,<span class="at">replace=</span><span class="cn">TRUE</span>)                   <span class="co"># generate new sample </span></span>
<span id="cb21-5"><a href="estimation.html#cb21-5" aria-hidden="true" tabindex="-1"></a>    phat <span class="ot">=</span> <span class="fu">mean</span>(x)                        </span>
<span id="cb21-6"><a href="estimation.html#cb21-6" aria-hidden="true" tabindex="-1"></a>    s <span class="ot">=</span> <span class="fu">sqrt</span>(phat<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>phat)<span class="sc">/</span><span class="dv">100</span>)           <span class="co"># see formula for CI of proportion above</span></span>
<span id="cb21-7"><a href="estimation.html#cb21-7" aria-hidden="true" tabindex="-1"></a>    poppar_in_ci[r] <span class="ot">=</span> phat <span class="sc">-</span><span class="fl">1.96</span> <span class="sc">*</span> s <span class="sc">&lt;</span> pop_par <span class="sc">&amp;</span> </span>
<span id="cb21-8"><a href="estimation.html#cb21-8" aria-hidden="true" tabindex="-1"></a>                        phat <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> s <span class="sc">&gt;</span> pop_par</span>
<span id="cb21-9"><a href="estimation.html#cb21-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb21-10"><a href="estimation.html#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(poppar_in_ci)</span></code></pre></div>
<pre><code>## [1] 0.933</code></pre>
<p>The result of this simulation shows that for approximately 95% of our samples, the constructed confidence interval indeed contains the population parameter value.</p>
<p>Note that in this case, we were sampling from a population we first generated. Often, we take samples just from a hypothetical population, where we assume that the samples are drawn from a distribution that captures the population. For example, in chapter 3 we directly made assumptions on the population distribution and sampled from the respective distributions.</p>
</div>
<div id="examples" class="section level3 hasAnchor" number="4.2.3">
<h3><span class="header-section-number">4.2.3</span> Examples<a href="estimation.html#examples" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>PROBLEM 1:</strong> A wine importer needs to report the average percentage of alcohol in bottles of French wine. From experience with previous kinds of wine, the importer believes that alcolhol percentages are normally distributed and the population standard deviation is 1.2%. The importer randomly samples 60 bottles of the new wine and obtains a sample mean <span class="math inline">\(\bar{x}=9.3\%\)</span>. Give a 90% confidence interval for the average percentage of alcohol in all bottles of the new wine.</p>
<details>
<summary>
Solution:
</summary>
<p>From the problem, we know the following.
<span class="math display">\[\begin{align*}
n = 60\\
\sigma=1.2\\
\bar{x} =9.3\\
\alpha=0.10
\end{align*}\]</span>
We must first figure out which type of confidence interval to use. Notice that we are trying to estimate the <em>average</em> percentage of alcohol, so our parameter is a mean <span class="math inline">\(\mu\)</span>. Moreover, we are told to assume that the data are normally distributed and the population standard deviation <span class="math inline">\(\sigma\)</span> is known. Thefore, our confidence interval will be of the form:
<span class="math display">\[\bar{x}\pm z_{\alpha/2}{\sigma\over\sqrt{n}}.\]</span>
We can now define each object in R and construct the confidence interval.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="estimation.html#cb23-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">60</span></span>
<span id="cb23-2"><a href="estimation.html#cb23-2" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">=</span> <span class="fl">1.2</span></span>
<span id="cb23-3"><a href="estimation.html#cb23-3" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">=</span> <span class="fl">9.3</span></span>
<span id="cb23-4"><a href="estimation.html#cb23-4" aria-hidden="true" tabindex="-1"></a>zalpha <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="fl">0.05</span>, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">1</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span>
<span id="cb23-5"><a href="estimation.html#cb23-5" aria-hidden="true" tabindex="-1"></a>xbar <span class="sc">-</span> zalpha<span class="sc">*</span>sigma<span class="sc">/</span><span class="fu">sqrt</span>(n)</span></code></pre></div>
<pre><code>## [1] 9.04518</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="estimation.html#cb25-1" aria-hidden="true" tabindex="-1"></a>xbar <span class="sc">+</span> zalpha<span class="sc">*</span>sigma<span class="sc">/</span><span class="fu">sqrt</span>(n)</span></code></pre></div>
<pre><code>## [1] 9.55482</code></pre>
<p>Therefore, we are 90% confident that the true average alcohol content in all new bottles of wine is between 9.05% and 9.55%.</p>
</details>
<p><br></p>
<p><strong>PROBLEM 2:</strong> An economist wants to estimate the average amount in checking accounts at banks in a given region. A random sample of 100 accounts gives <span class="math inline">\(\bar{x}=£357.60\)</span> and <span class="math inline">\(s=£140.00\)</span>. Give a 95% confidence interval for <span class="math inline">\(\mu\)</span>, the average amount in any checking account at a bank in the given region.</p>
<details>
<summary>
Solution:
</summary>
<p>From the problem, we know the following.
<span class="math display">\[\begin{align*}
n &amp;= 100\\
\bar{x} &amp;=357.60\\
s &amp;= 140\\
\alpha&amp;=0.5
\end{align*}\]</span>
Here we are not told whether the data are normally distributed. However, it won’t matter because we only have an estimate of <span class="math inline">\(\sigma\)</span> (remember that among the four types of confidence intervals we considered earlier, there are no differences between case II and III). Therefore, our confidence interval will be of the form:
<span class="math display">\[\bar{x}\pm t_{n-1,\alpha/2}{s\over\sqrt{n}}.\]</span>
We can again define each object in R and construct the confidence interval.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="estimation.html#cb27-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">100</span></span>
<span id="cb27-2"><a href="estimation.html#cb27-2" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">=</span> <span class="fl">357.60</span></span>
<span id="cb27-3"><a href="estimation.html#cb27-3" aria-hidden="true" tabindex="-1"></a>s <span class="ot">=</span> <span class="dv">140</span></span>
<span id="cb27-4"><a href="estimation.html#cb27-4" aria-hidden="true" tabindex="-1"></a>talpha <span class="ot">=</span> <span class="fu">qt</span>(<span class="fl">0.025</span>, <span class="at">df=</span>n<span class="dv">-1</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span>
<span id="cb27-5"><a href="estimation.html#cb27-5" aria-hidden="true" tabindex="-1"></a>xbar <span class="sc">-</span> talpha<span class="sc">*</span>s<span class="sc">/</span><span class="fu">sqrt</span>(n)</span></code></pre></div>
<pre><code>## [1] 329.821</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="estimation.html#cb29-1" aria-hidden="true" tabindex="-1"></a>xbar <span class="sc">+</span> talpha<span class="sc">*</span>s<span class="sc">/</span><span class="fu">sqrt</span>(n)</span></code></pre></div>
<pre><code>## [1] 385.379</code></pre>
<p>Therefore, we are 95% confident that the true average account checking account value in the given region is between £329.82 and £385.38.</p>
</details>
<p><br></p>
<p><strong>PROBLEM 3:</strong> The EuStockMarkets data set in R provides daily closing prices of four major European stock indices: Germany DAX (Ibis), Switzerland SMI, France CAC, and UK FTSE. Using this data set, produce a 99% confidence interval for the average closing price of the UK FTSE.</p>
<details>
<summary>
Solution:
</summary>
<p>First, let’s load in the data from R.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="estimation.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(EuStockMarkets)</span>
<span id="cb31-2"><a href="estimation.html#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(EuStockMarkets)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
DAX
</th>
<th style="text-align:right;">
SMI
</th>
<th style="text-align:right;">
CAC
</th>
<th style="text-align:right;">
FTSE
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1628.75
</td>
<td style="text-align:right;">
1678.1
</td>
<td style="text-align:right;">
1772.8
</td>
<td style="text-align:right;">
2443.6
</td>
</tr>
<tr>
<td style="text-align:right;">
1613.63
</td>
<td style="text-align:right;">
1688.5
</td>
<td style="text-align:right;">
1750.5
</td>
<td style="text-align:right;">
2460.2
</td>
</tr>
<tr>
<td style="text-align:right;">
1606.51
</td>
<td style="text-align:right;">
1678.6
</td>
<td style="text-align:right;">
1718.0
</td>
<td style="text-align:right;">
2448.2
</td>
</tr>
<tr>
<td style="text-align:right;">
1621.04
</td>
<td style="text-align:right;">
1684.1
</td>
<td style="text-align:right;">
1708.1
</td>
<td style="text-align:right;">
2470.4
</td>
</tr>
<tr>
<td style="text-align:right;">
1618.16
</td>
<td style="text-align:right;">
1686.6
</td>
<td style="text-align:right;">
1723.1
</td>
<td style="text-align:right;">
2484.7
</td>
</tr>
<tr>
<td style="text-align:right;">
1610.61
</td>
<td style="text-align:right;">
1671.6
</td>
<td style="text-align:right;">
1714.3
</td>
<td style="text-align:right;">
2466.8
</td>
</tr>
</tbody>
</table>
<p>Now let’s pull the subset of data we care about (i.e., the UK FTSE column).</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="estimation.html#cb32-1" aria-hidden="true" tabindex="-1"></a>uk <span class="ot">=</span> EuStockMarkets[,<span class="dv">4</span>]</span></code></pre></div>
<p>Notice that we are not told anything about the true distribution of the data. Therefore, our confidence interval will be of the form:
<span class="math display">\[\bar{x}\pm t_{n-1,\alpha/2}{s\over\sqrt{n}}.\]</span>
Next, let’s compute each component necessary to construct the 99% confidence interval.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="estimation.html#cb33-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">length</span>(uk)</span>
<span id="cb33-2"><a href="estimation.html#cb33-2" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">=</span> <span class="fu">mean</span>(uk)</span>
<span id="cb33-3"><a href="estimation.html#cb33-3" aria-hidden="true" tabindex="-1"></a>s <span class="ot">=</span> <span class="fu">sd</span>(uk)</span>
<span id="cb33-4"><a href="estimation.html#cb33-4" aria-hidden="true" tabindex="-1"></a>talpha <span class="ot">=</span> <span class="fu">qt</span>(<span class="fl">0.005</span>, <span class="at">df=</span>n<span class="dv">-1</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span>
<span id="cb33-5"><a href="estimation.html#cb33-5" aria-hidden="true" tabindex="-1"></a>xbar <span class="sc">-</span> talpha<span class="sc">*</span>s<span class="sc">/</span><span class="fu">sqrt</span>(n)</span></code></pre></div>
<pre><code>## [1] 3507.248</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="estimation.html#cb35-1" aria-hidden="true" tabindex="-1"></a>xbar <span class="sc">+</span> talpha<span class="sc">*</span>s<span class="sc">/</span><span class="fu">sqrt</span>(n)</span></code></pre></div>
<pre><code>## [1] 3624.038</code></pre>
<p>Therefore, we are 99% confident that the true closing price for the UK FTSE index is between £3,507.25 and £3,624.04.</p>
<p>Finally, notice that we can use the <code>t.test( )</code> function to perform the same analysis but with fewer ste</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sampling-distributions-and-the-clt.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="hypothesis-tests.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
